language:
    csharp

install:
    - sudo apt-get install nunit-console

script:
    - xbuild ./Authorize.NET/AuthorizeNET.csproj
    - xbuild ./AuthorizeNETtest/AuthorizeNETtest.csproj
#   make mono happy by copying the config file with project name
    - cp AuthorizeNETtest/App.config AuthorizeNETtest/AuthorizeNETtest.config
    - nunit-console ./AuthorizeNETtest/AuthorizeNETtest.csproj -run=AuthorizeNet.Api.Controllers.MockTest -exclude Integration,NotWorkingOnMono
